extends Node

const GUI_SET_NAME = "GAME_SET_NAME"

const PLAYER_CONNECTED = "PLAYER_CONNECTED"
const PLAYER_DISCONNECTED = "PLAYER_DISCONNECTED"
const PLAYER_SPAWN = "PLAYER_SPAWN"
const PLAYER_MOVE = "PLAYER_MOVE"

const SHIP_LOAD = "SHIP_LOAD"
