extends Node

const GUI_SET_NAME = "GAME_SET_NAME"

const PLAYER_CONNECTED = "PLAYER_CONNECTED"
const PLAYER_DISCONNECTED = "PLAYER_DISCONNECTED"

const ENTITY_SPAWN = "ENTITY_SPAWN"
const ENTITY_MOVE = "ENTITY_MOVE"

const SHIP_LOAD = "SHIP_LOAD"
