extends Node

const GAME_START = "GAME_START"
const ROUND_START = "ROUND_START"
const ROUND_END = "ROUND_END"

const PLAYER_CONNECTED = "PLAYER_CONNECTED"
const PLAYER_DISCONNECTED = "PLAYER_DISCONNECTED"

const ENTITY_SPAWN = "ENTITY_SPAWN"
const ENTITY_MOVE = "ENTITY_MOVE"

const SHIP_LOAD = "SHIP_LOAD"
